name: falcon-shield-prod
services:
  webapi:
    container_name: webapi
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - falcon-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - keycloak
      - kafka1

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    command: start
    ports:
      - 8081:8080
      - 8443:8443
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HOSTNAME: https://auth.falcon-shield.tech
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin_user
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123
    networks:
      - falcon-network

networks:
  falcon-network:
    driver: bridge

#ejecutar:
#docker compose -f docker-compose.yml up -d