name: falcon-shield-keycloak-dev
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-dev
    restart: always
    command: start-dev
    ports:
      - 9090:8080
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - keycloak-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  keycloak-network:
    driver: bridge
